### ISSUE TITLE
Limit domains for domain_access field on nodes

### ISSUE THREAD

**Issue by franzwilding** [agentrickard/domain#34] opened 2015-02-17 10:37 UTC
We need to limit the domains to the ones, the user is assigned to. I think this can only be done by creating a custom entity reference handler for the domain_access fields: 

    $field = array(
        ...
        'settings' => array(
          'handler' => 'domain_access', 
        ),
    );

**Comment by agentrickard** [comment] 2015-02-17 14:23
This is an advanced feature but necessary.

**Comment by franzwilding** [comment] 2015-02-17 15:33
There was an DomainSelection not following the Plugin autoload naming convention. I changed this, moved it to domain_access and added some lines of code to check against user assigned domains. 

I tested this manually, but I think we need more logic on the query and automated testing.

With this changes the DomainSelection will only show the user domains only. We may need an permission like "can publish content on other domains" to create content for other domains, or maybe an "can publish content on all domains" permission. "administer domains" is not the right choice in my opinion. What do you think?

**Comment by franzwilding** [comment] 2015-02-24 10:33
What do you think about moving the EntityReferenceSelection? An other way would be to create two selections, one default selection, living in the domain module and another selection for domain access. Then you select the EntityReferenceSelection in the field settings.

**Comment by agentrickard** [comment] 2015-02-24 18:00
A couple of notes:

*  Not all the D7 module permissions have been moved over yet -- especially the trinity of "publish to any ..." permissions. Those are the ones the are relevant here. Really, these five from D7 are applicable:

```
    'assign domain editors' => array(
      'title' => t('Assign editors to domains'),
    ),
    'set domain access' => array(
      'title' => t('Set domain access status for all content'),
    ),
    'publish to any assigned domain' => array(
      'title' => t('Publish content to any assigned domain'),
    ),
    'publish from assigned domain' => array(
      'title' => t('Publish content only from assigned domain'),
    ),
    'publish from default domain' => array(
      'title' => t('Publish content only from the default domain'),
    ),
```

* If the selection widget can have settings, I would think that one widget with different settings would be fine. That widget should be owned by the main module, and its implementation config handled by sub modules. Though it may be that there are no settings, just permission-based behavior based on context.

**Comment by agentrickard** [comment] 2015-03-01 16:04
Opened up branch 34-selector for this.

**Comment by agentrickard** [comment] 2015-03-06 23:10
Moving the EntityReferenceSelection flat out fails, because SelectionBase does not support Config Entities. That means that the default settings for the field never appear.

I _think_ this is being addressed in https://www.drupal.org/node/2436835

All of the config entities that "work" with Entity Reference do not provide their own Selection plugin.

The problem, I think, is in SelectionBase, line 145:

```
if ($entity_type->isSubclassOf('\Drupal\Core\Entity\FieldableEntityInterface')) {
```

Well, config entities, by definition, as not Fieldable.

**Comment by agentrickard** [comment] 2015-03-20 17:24
I am now very conflicted about whether we should be using Config entities or Content entities. 

We lose a number of features (Views integration most notably; fieldability) by using Config, which still seems proper. But if we can't properly use EntityReference, we may have to resort to our own field handler. And I don't want to do that.

**Comment by jweirather** [comment] 2015-03-20 17:47
I'm sure I don't fully grasp the potential outcomes of this decision(s), but I wanted to offer my $0.02 that, in general, fieldability is one of the most exciting (expected) upgrades I see for my use cases, and I'm pretty sure deep views integration is a must for most of us. If it were up to me, that would be the guiding principle and any exceptions would have to overcome that need.

In my own implementation, I could even argue that domains themselves are actually content masquerading as a configuration. I'm sure this varies widely based on use cases, but wanted to chime in. 

Again, I'm not sure I understand the issue at hand, but thought to chime in.

**Comment by agentrickard** [comment] 2015-03-20 18:19
Those are the main issues. From a structural point-of-view, domains are more akin to Vocabularies than Nodes, and I think the early experiments show that config entities may not be suitable.

The argument for config entities, generally, is that they are _exportable_, which is the other most important feature people ask for, one might argue (and we did) that exportability is more important than fieldability.

Views support could be added in a later module that reads the config data into a format Views can manipulate.

When planning the work for D8, we had to choose one or the other if we want to use the Entity system. This was a conversation I had with Alex Pott and some of the other core maintainers at DevDays in Dublin, so we went with Config Entities.

**Comment by agentrickard** [comment] 2015-03-20 18:20
Look at taxonomy module for the use-cases for the two types. It's a good analogy for what we're doing.

Term is a Content Entity, but Vocabulary is a Config Entity.

**Comment by agentrickard** [comment] 2015-03-20 18:22
See this very telling code comment, in TermSelection.php, which is directly relevant to this specific issue of Entity reference.

```
class TermSelection extends SelectionBase {

  /**
   * {@inheritdoc}
   */
  public function entityQueryAlter(SelectInterface $query) {
    // @todo: How to set access, as vocabulary is now config?
  }
```

**Comment by agentrickard** [comment] 2015-03-20 19:50
In order of preference, here's what I think is most important:

# Exportables
# Views
# Fields

The Views issue is fixable, even with Config Entities, but the lack of support for access control on Config Entities may push us into Content Entities.

**Comment by jweirather** [comment] 2015-03-20 21:58
Thanks for the thoughtful replies, I'll digest those and see if anything comes to mind. I'm really just trying to help brainstorm, and not advocating for any particular outcome.

Please forgive another partially informed question or two: In what general context (or use case) is exportability so important for domain? And can it (should it) be dealt with effectively outside of core?

I'm guessing that I'm not thinking about exportables the same way others might, which might change my $0.02. FWIW.

**Comment by agentrickard** [comment] 2015-03-21 21:50
The argument about exportables is that domain configurations can radically change the behavior of your site, so being able to reliably replicate those across a dev -> stage -> production workflow is critical. More critical than advanced functionality.

It is similar to being able to export/import Panels configuration. It is possible that Features in D8 will make this possible for Content Entities, given that we have native UUID support. 

From a philosophical perspective, the core maintainers I spoke with considered Config Entities most appropriate, though this module definitely shows the problem(s) of edge cases.

**Comment by jweirather** [comment] 2015-03-23 18:41
The exportables argument makes perfect sense. I do have the same workflow, but I move the whole site in one unit (for now), so that's not an issue I've faced just yet. That said, an interface like those in Views or Panels for import/export, or cloning, migrate, etc., would probably do the job for my specific case. Especially if Features can mitigate this in the future.

After reading a bit more about these two entity types, it seems to me now that by its strictest definition and most limited implementation, Domain would clearly be a Config Entity. However, the beauty of the module is its extendability, and the more a site actually uses it and leverages certain features and submodules, access control, fields, views, panels, etc, the more Domain appears to be a Content Entity.

On that note, just so I'm clear, are we talking about Domain in general, or just the specific features dealt with by this thread?

Can Domain be *both*, like your Taxonomy reference above? One set of features as Config Entities, another set as Content? 

Speaking of Taxonomy, I believe I mentioned this once before, but treating domains like taxonomy terms (nesting with content inheritance) would also be a great feature (if it's not already). I know it's off topic.

[/random thoughts]

**Comment by agentrickard** [comment] 2015-03-23 19:06
Well, this discussion just branches from the issue here. The behavior of Entity Reference just threw new light on the problem.

In theory, we could make the base domain a Config Entity, and layer everything on top as a Content Entity -- though right now, Domain Alias also uses Config Entities. The problem is still exportables, which I think trump other features.

**Comment by jweirather** [comment] 2015-03-23 20:27
Understood. I know we were (I was) going off topic.

**Comment by agentrickard** [comment] 2015-11-15 15:30
Config Entities caught up, and this now works.

**Closed by agentrickard** 2015-11-15 15:30 UTC
