### ISSUE TITLE
Blocks disappears after database update

### ISSUE THREAD

**Issue by crtlf** [agentrickard/domain#457] opened 2018-11-08 08:10 UTC
After a Core (8.6.2) and Domain Access update, all of my blocks have disappeared. Looks like a Domain issue because the bug doesn't appears in several others Drupal 8 that I updated, except those with the Domain Access module.

I've made some tests, and I understand that the bug is caused by the database update 8001 with version 1.0-alpha14.

### Versions

Before the update :

- Drupal : 8.6.1
- Domain : 8.x-1.0-alpha13

After the update :

- Drupal : 8.6.2
- Domain : 8.x-1.0-alpha14

### Explanations

In the back-office, all my blocks are here and I see no changes in their configurations.
The only difference I noticed between a visible block and a hidden one is the `visibility > domain > context_mapping` array.

This array is empty in my hidden blocks...
![](https://www.drupal.org/files/issues/2018-11-02/hidden-block.png)

... and not when my block is visible
![](https://www.drupal.org/files/issues/2018-11-02/visible-block.png)

**Comment by dpagini** [comment] 2018-11-08 15:24
I believe this is the same or similar problem I was having in #455. Would you see if that change will fix your problem here...?

**Comment by dpagini** [comment] 2018-11-09 15:44
Awesome. I think I saw @agentrickard say he was going on a vacation a week or two back, so hopefully when he returns he may be able to shed some light on that one. I'm going to add a link over in that issue to close this one when it gets merged, if that's OK with you?

**Comment by crtlf** [comment] 2018-11-09 15:46
It's perfect !

**Comment by agentrickard** [comment] 2018-11-14 15:20
These changes are not related to domain_update_8001(), and the issue is handled over in #455.

**Closed by agentrickard** 2018-11-14 15:20 UTC
